import { AircraftType } from '../types';

export const aircraftTypes: AircraftType[] = [
  {
    id: 'fixed-wing',
    name: 'Fixed Wing',
    icon: 'Plane',
    category: 'fixed-wing',
    wingspan: 120,
    weight: 500,
    wingArea: 1500,
    aspectRatio: 6.5,
    motorPower: 100,
    battery: 2200,
    voltage: 11.1,
    bestFor: 'General flying, training',
    cd0: 0.025,
    clMax: 1.2,
    Oswald: 0.8,
  },
  {
    id: 'quadcopter',
    name: 'Quadcopter',
    icon: 'Wind',
    category: 'multirotor',
    wingspan: 250,
    weight: 800,
    wingArea: 2500,
    aspectRatio: 1,
    motorPower: 200,
    battery: 3000,
    voltage: 11.1,
    bestFor: 'Aerial photography, stable footage',
    cd0: 0.08,
    clMax: 1.0,
    Oswald: 0.5,
  },
  {
    id: 'hexacopter',
    name: 'Hexacopter',
    icon: 'Hexagon',
    category: 'multirotor',
    wingspan: 450,
    weight: 1500,
    wingArea: 4500,
    aspectRatio: 1,
    motorPower: 400,
    battery: 5000,
    voltage: 22.2,
    bestFor: 'Heavy lift, professional work',
    cd0: 0.1,
    clMax: 0.9,
    Oswald: 0.5,
  },
  {
    id: 'vtol',
    name: 'VTOL',
    icon: 'ArrowUpDown',
    category: 'fixed-wing',
    wingspan: 100,
    weight: 600,
    wingArea: 1200,
    aspectRatio: 5.5,
    motorPower: 150,
    battery: 3000,
    voltage: 14.8,
    bestFor: 'Vertical takeoff, transition flight',
    cd0: 0.03,
    clMax: 1.1,
    Oswald: 0.75,
  },
  {
    id: 'helicopter',
    name: 'Helicopter',
    icon: 'RotateCw',
    category: 'rotor',
    wingspan: 80,
    weight: 400,
    wingArea: 800,
    aspectRatio: 0.8,
    motorPower: 80,
    battery: 1500,
    voltage: 11.1,
    bestFor: '3D flying, precision maneuvers',
    cd0: 0.035,
    clMax: 1.3,
    Oswald: 0.7,
  },
  {
    id: 'sailplane',
    name: 'Sailplane',
    icon: 'Feather',
    category: 'fixed-wing',
    wingspan: 180,
    weight: 300,
    wingArea: 3000,
    aspectRatio: 10.8,
    motorPower: 50,
    battery: 1000,
    voltage: 7.4,
    bestFor: 'Thermal soaring, long flights',
    cd0: 0.02,
    clMax: 1.4,
    Oswald: 0.85,
  },
  {
    id: 'delta-wing',
    name: 'Delta Wing',
    icon: 'Triangle',
    category: 'fixed-wing',
    wingspan: 80,
    weight: 450,
    wingArea: 1000,
    aspectRatio: 4.5,
    motorPower: 90,
    battery: 1800,
    voltage: 11.1,
    bestFor: 'Fast flight, sport flying',
    cd0: 0.028,
    clMax: 1.1,
    Oswald: 0.78,
  },
  {
    id: 'biplane',
    name: 'Biplane',
    icon: 'Layers',
    category: 'fixed-wing',
    wingspan: 100,
    weight: 700,
    wingArea: 1800,
    aspectRatio: 5.5,
    motorPower: 120,
    battery: 2200,
    voltage: 11.1,
    bestFor: 'Scale flying, nostalgic appeal',
    cd0: 0.035,
    clMax: 1.15,
    Oswald: 0.75,
  },
  {
    id: 'flying-wing',
    name: 'Flying Wing',
    icon: 'ArrowRight',
    category: 'fixed-wing',
    wingspan: 140,
    weight: 400,
    wingArea: 1600,
    aspectRatio: 12.2,
    motorPower: 80,
    battery: 1800,
    voltage: 11.1,
    bestFor: 'Speed, efficiency',
    cd0: 0.022,
    clMax: 0.9,
    Oswald: 0.9,
  },
  {
    id: 'park-flyer',
    name: 'Park Flyer',
    icon: 'Bird',
    category: 'fixed-wing',
    wingspan: 90,
    weight: 200,
    wingArea: 800,
    aspectRatio: 5.0,
    motorPower: 30,
    battery: 800,
    voltage: 7.4,
    bestFor: 'Beginners, small spaces',
    cd0: 0.03,
    clMax: 1.25,
    Oswald: 0.8,
  },
  {
    id: 'warbird',
    name: 'Warbird',
    icon: 'Award',
    category: 'fixed-wing',
    wingspan: 140,
    weight: 1200,
    wingArea: 2500,
    aspectRatio: 7.8,
    motorPower: 250,
    battery: 4000,
    voltage: 14.8,
    bestFor: 'Scale realism, historical',
    cd0: 0.032,
    clMax: 1.2,
    Oswald: 0.78,
  },
  {
    id: 'jet-turbine',
    name: 'Jet Turbine',
    icon: 'Zap',
    category: 'fixed-wing',
    wingspan: 130,
    weight: 1800,
    wingArea: 2200,
    aspectRatio: 7.7,
    motorPower: 400,
    battery: 0,
    voltage: 0,
    bestFor: 'High speed, realistic jets',
    cd0: 0.04,
    clMax: 1.0,
    Oswald: 0.82,
  },
  {
    id: 'tricopter',
    name: 'Tricopter',
    icon: 'Triangle',
    category: 'multirotor',
    wingspan: 200,
    weight: 500,
    wingArea: 2000,
    aspectRatio: 1,
    motorPower: 120,
    battery: 2200,
    voltage: 11.1,
    bestFor: 'Lightweight, agile',
    cd0: 0.07,
    clMax: 1.0,
    Oswald: 0.5,
  },
  {
    id: 'octocopter',
    name: 'Octocopter',
    icon: 'Octagon',
    category: 'multirotor',
    wingspan: 600,
    weight: 3000,
    wingArea: 8000,
    aspectRatio: 1,
    motorPower: 800,
    battery: 8000,
    voltage: 22.2,
    bestFor: 'Cinematography, heavy payload',
    cd0: 0.12,
    clMax: 0.85,
    Oswald: 0.45,
  },
  {
    id: 'balloon',
    name: 'Hot Air Balloon',
    icon: 'CircleDot',
    category: 'special',
    wingspan: 100,
    weight: 100,
    wingArea: 5000,
    aspectRatio: 0.2,
    motorPower: 20,
    battery: 500,
    voltage: 3.7,
    bestFor: 'Indoor, casual',
    cd0: 0.015,
    clMax: 0.6,
    Oswald: 0.6,
  },
];

export function getAircraftById(id: string): AircraftType | undefined {
  return aircraftTypes.find(a => a.id === id);
}

export function getAircraftByCategory(category: AircraftType['category']): AircraftType[] {
  return aircraftTypes.filter(a => a.category === category);
}
